[project]
name = "mast"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "astropy>=7.1.0",
    "astroquery>=0.4.10",
    "matplotlib>=3.10.5",
    "streamlit>=1.48.1",
]
